/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : usb_device.c
  * @version        : v1.0_Cube
  * @brief          : This file implements the USB Device
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under Ultimate Liberty license
  * SLA0044, the "License"; You may not use this file except in compliance with
  * the License. You may obtain a copy of the License at:
  *                             www.st.com/SLA0044
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/

#include "usb_device.h"
#include "usbd_core.h"
#include "usbd_desc.h"
#include "usbd_RTT_class.h"

/* USB Device Core handle declaration. */
USBD_HandleTypeDef hUsbDeviceHS;

/**
  * Init USB device Library, add supported class
  * @retval None
  */
void MX_USB_DEVICE_Init(void)
{

  /* Init Device Library, add supported class. */
  // WARNING: This function also indirectly  sets the RX and TX fifos (the actual call is USBD_LL_Init in usbd_conf.c). The default values generated by CUBEMX are not alway right.
  // The stm32F7 has 4kB of shared RAM for these fifos, so the sum of all the Fifo buffers cannot exceed this value. The sizes passed are in words (32 bits), so multiply with 4 for the actual size
  if (USBD_Init(&hUsbDeviceHS, &RTT_Desc, DEVICE_HS) != USBD_OK)
  {
    Error_Handler();
  }
  if (USBD_RegisterClass(&hUsbDeviceHS, &USBD_RTT_ClassDriver) != USBD_OK)
  {
    Error_Handler();
  }
}

void USB_Start_Class(USBD_RTT_Callbacks* callbacks){
  if(callbacks == NULL){
    Error_Handler();
  }
  // assign user callback functions
  hUsbDeviceHS.pUserData = callbacks;
  // start USB device
  if (USBD_Start(&hUsbDeviceHS) != USBD_OK)
  {
    Error_Handler();
  }
}
