# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AIData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AIData.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x41IData.proto\x12\x05proto\"d\n\tRobotPath\x12\x10\n\x08robot_id\x18\x01 \x01(\x05\x12&\n\x06points\x18\x02 \x03(\x0b\x32\x16.proto.RobotPath.Point\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x8b\x01\n\x08RobotSTP\x12\x10\n\x08robot_id\x18\x01 \x01(\x05\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x13\n\x0brole_status\x18\x03 \x01(\t\x12\x0e\n\x06tactic\x18\x04 \x01(\t\x12\x15\n\rtactic_status\x18\x05 \x01(\t\x12\r\n\x05skill\x18\x06 \x01(\t\x12\x14\n\x0cskill_status\x18\x07 \x01(\t\"T\n\x06\x41IData\x12#\n\nrobot_stps\x18\x01 \x03(\x0b\x32\x0f.proto.RobotSTP\x12%\n\x0brobot_paths\x18\x02 \x03(\x0b\x32\x10.proto.RobotPathb\x06proto3'
)




_ROBOTPATH_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='proto.RobotPath.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.RobotPath.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.RobotPath.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=123,
)

_ROBOTPATH = _descriptor.Descriptor(
  name='RobotPath',
  full_name='proto.RobotPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='proto.RobotPath.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='proto.RobotPath.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ROBOTPATH_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=123,
)


_ROBOTSTP = _descriptor.Descriptor(
  name='RobotSTP',
  full_name='proto.RobotSTP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='proto.RobotSTP.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='proto.RobotSTP.role', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role_status', full_name='proto.RobotSTP.role_status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tactic', full_name='proto.RobotSTP.tactic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tactic_status', full_name='proto.RobotSTP.tactic_status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill', full_name='proto.RobotSTP.skill', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_status', full_name='proto.RobotSTP.skill_status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=265,
)


_AIDATA = _descriptor.Descriptor(
  name='AIData',
  full_name='proto.AIData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_stps', full_name='proto.AIData.robot_stps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robot_paths', full_name='proto.AIData.robot_paths', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=351,
)

_ROBOTPATH_POINT.containing_type = _ROBOTPATH
_ROBOTPATH.fields_by_name['points'].message_type = _ROBOTPATH_POINT
_AIDATA.fields_by_name['robot_stps'].message_type = _ROBOTSTP
_AIDATA.fields_by_name['robot_paths'].message_type = _ROBOTPATH
DESCRIPTOR.message_types_by_name['RobotPath'] = _ROBOTPATH
DESCRIPTOR.message_types_by_name['RobotSTP'] = _ROBOTSTP
DESCRIPTOR.message_types_by_name['AIData'] = _AIDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotPath = _reflection.GeneratedProtocolMessageType('RobotPath', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _ROBOTPATH_POINT,
    '__module__' : 'AIData_pb2'
    # @@protoc_insertion_point(class_scope:proto.RobotPath.Point)
    })
  ,
  'DESCRIPTOR' : _ROBOTPATH,
  '__module__' : 'AIData_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotPath)
  })
_sym_db.RegisterMessage(RobotPath)
_sym_db.RegisterMessage(RobotPath.Point)

RobotSTP = _reflection.GeneratedProtocolMessageType('RobotSTP', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTP,
  '__module__' : 'AIData_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotSTP)
  })
_sym_db.RegisterMessage(RobotSTP)

AIData = _reflection.GeneratedProtocolMessageType('AIData', (_message.Message,), {
  'DESCRIPTOR' : _AIDATA,
  '__module__' : 'AIData_pb2'
  # @@protoc_insertion_point(class_scope:proto.AIData)
  })
_sym_db.RegisterMessage(AIData)


# @@protoc_insertion_point(module_scope)
