# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Handshake.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.UiOptions_pb2 as UiOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Handshake.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fHandshake.proto\x12\x05proto\x1a\x0fUiOptions.proto\"t\n\tHandshake\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x31\n\x0c\x64\x65\x63larations\x18\x02 \x01(\x0b\x32\x1b.proto.UiOptionDeclarations\x12\x1f\n\x06values\x18\x03 \x01(\x0b\x32\x0f.proto.UiValuesb\x06proto3'
  ,
  dependencies=[UiOptions__pb2.DESCRIPTOR,])




_HANDSHAKE = _descriptor.Descriptor(
  name='Handshake',
  full_name='proto.Handshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_name', full_name='proto.Handshake.module_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='declarations', full_name='proto.Handshake.declarations', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='proto.Handshake.values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=159,
)

_HANDSHAKE.fields_by_name['declarations'].message_type = UiOptions__pb2._UIOPTIONDECLARATIONS
_HANDSHAKE.fields_by_name['values'].message_type = UiOptions__pb2._UIVALUES
DESCRIPTOR.message_types_by_name['Handshake'] = _HANDSHAKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Handshake = _reflection.GeneratedProtocolMessageType('Handshake', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKE,
  '__module__' : 'Handshake_pb2'
  # @@protoc_insertion_point(class_scope:proto.Handshake)
  })
_sym_db.RegisterMessage(Handshake)


# @@protoc_insertion_point(module_scope)
