# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotProcessedFeedback.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotProcessedFeedback.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cRobotProcessedFeedback.proto\x12\x05proto\"-\n\nRobotWheel\x12\x0e\n\x06locked\x18\x01 \x01(\x08\x12\x0f\n\x07\x62raking\x18\x02 \x01(\x08\"\xa5\x01\n\x0bRobotWheels\x12%\n\nrightFront\x18\x01 \x01(\x0b\x32\x11.proto.RobotWheel\x12$\n\trightBack\x18\x02 \x01(\x0b\x32\x11.proto.RobotWheel\x12#\n\x08leftBack\x18\x03 \x01(\x0b\x32\x11.proto.RobotWheel\x12$\n\tleftFront\x18\x04 \x01(\x0b\x32\x11.proto.RobotWheel\"\xa3\x02\n\x16RobotProcessedFeedback\x12\x1d\n\x15\x62\x61ll_sensor_sees_ball\x18\x01 \x01(\x08\x12\x15\n\rball_position\x18\x02 \x01(\x02\x12\x1e\n\x16\x62\x61ll_sensor_is_working\x18\x03 \x01(\x08\x12\x1a\n\x12\x64ribbler_sees_ball\x18\x04 \x01(\x08\x12\x1b\n\x13xsens_is_calibrated\x18\x05 \x01(\x08\x12\x1c\n\x14\x63\x61pacitor_is_charged\x18\x06 \x01(\x08\x12,\n\x10wheelInformation\x18\x07 \x01(\x0b\x32\x12.proto.RobotWheels\x12\x15\n\rbattery_level\x18\x08 \x01(\x02\x12\x17\n\x0fsignal_strength\x18\t \x01(\x05\"P\n\x11\x46\x65\x65\x64\x62\x61\x63kOnlyRobot\x12\n\n\x02id\x18\x01 \x01(\x05\x12/\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\x0b\x32\x1d.proto.RobotProcessedFeedbackb\x06proto3'
)




_ROBOTWHEEL = _descriptor.Descriptor(
  name='RobotWheel',
  full_name='proto.RobotWheel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locked', full_name='proto.RobotWheel.locked', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='braking', full_name='proto.RobotWheel.braking', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=84,
)


_ROBOTWHEELS = _descriptor.Descriptor(
  name='RobotWheels',
  full_name='proto.RobotWheels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rightFront', full_name='proto.RobotWheels.rightFront', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rightBack', full_name='proto.RobotWheels.rightBack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leftBack', full_name='proto.RobotWheels.leftBack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leftFront', full_name='proto.RobotWheels.leftFront', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=252,
)


_ROBOTPROCESSEDFEEDBACK = _descriptor.Descriptor(
  name='RobotProcessedFeedback',
  full_name='proto.RobotProcessedFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ball_sensor_sees_ball', full_name='proto.RobotProcessedFeedback.ball_sensor_sees_ball', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_position', full_name='proto.RobotProcessedFeedback.ball_position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_sensor_is_working', full_name='proto.RobotProcessedFeedback.ball_sensor_is_working', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dribbler_sees_ball', full_name='proto.RobotProcessedFeedback.dribbler_sees_ball', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xsens_is_calibrated', full_name='proto.RobotProcessedFeedback.xsens_is_calibrated', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacitor_is_charged', full_name='proto.RobotProcessedFeedback.capacitor_is_charged', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheelInformation', full_name='proto.RobotProcessedFeedback.wheelInformation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='proto.RobotProcessedFeedback.battery_level', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal_strength', full_name='proto.RobotProcessedFeedback.signal_strength', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=546,
)


_FEEDBACKONLYROBOT = _descriptor.Descriptor(
  name='FeedbackOnlyRobot',
  full_name='proto.FeedbackOnlyRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.FeedbackOnlyRobot.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='proto.FeedbackOnlyRobot.feedback', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=628,
)

_ROBOTWHEELS.fields_by_name['rightFront'].message_type = _ROBOTWHEEL
_ROBOTWHEELS.fields_by_name['rightBack'].message_type = _ROBOTWHEEL
_ROBOTWHEELS.fields_by_name['leftBack'].message_type = _ROBOTWHEEL
_ROBOTWHEELS.fields_by_name['leftFront'].message_type = _ROBOTWHEEL
_ROBOTPROCESSEDFEEDBACK.fields_by_name['wheelInformation'].message_type = _ROBOTWHEELS
_FEEDBACKONLYROBOT.fields_by_name['feedback'].message_type = _ROBOTPROCESSEDFEEDBACK
DESCRIPTOR.message_types_by_name['RobotWheel'] = _ROBOTWHEEL
DESCRIPTOR.message_types_by_name['RobotWheels'] = _ROBOTWHEELS
DESCRIPTOR.message_types_by_name['RobotProcessedFeedback'] = _ROBOTPROCESSEDFEEDBACK
DESCRIPTOR.message_types_by_name['FeedbackOnlyRobot'] = _FEEDBACKONLYROBOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotWheel = _reflection.GeneratedProtocolMessageType('RobotWheel', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTWHEEL,
  '__module__' : 'RobotProcessedFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotWheel)
  })
_sym_db.RegisterMessage(RobotWheel)

RobotWheels = _reflection.GeneratedProtocolMessageType('RobotWheels', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTWHEELS,
  '__module__' : 'RobotProcessedFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotWheels)
  })
_sym_db.RegisterMessage(RobotWheels)

RobotProcessedFeedback = _reflection.GeneratedProtocolMessageType('RobotProcessedFeedback', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTPROCESSEDFEEDBACK,
  '__module__' : 'RobotProcessedFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotProcessedFeedback)
  })
_sym_db.RegisterMessage(RobotProcessedFeedback)

FeedbackOnlyRobot = _reflection.GeneratedProtocolMessageType('FeedbackOnlyRobot', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACKONLYROBOT,
  '__module__' : 'RobotProcessedFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.FeedbackOnlyRobot)
  })
_sym_db.RegisterMessage(FeedbackOnlyRobot)


# @@protoc_insertion_point(module_scope)
