# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: State.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.World_pb2 as World__pb2
import proto.RobotParameters_pb2 as RobotParameters__pb2
import proto.messages_robocup_ssl_wrapper_pb2 as messages__robocup__ssl__wrapper__pb2
import proto.messages_robocup_ssl_referee_pb2 as messages__robocup__ssl__referee__pb2
import proto.messages_robocup_ssl_geometry_pb2 as messages__robocup__ssl__geometry__pb2
import proto.Handshake_pb2 as Handshake__pb2
import proto.UiOptions_pb2 as UiOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='State.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bState.proto\x12\x05proto\x1a\x0bWorld.proto\x1a\x15RobotParameters.proto\x1a\"messages_robocup_ssl_wrapper.proto\x1a\"messages_robocup_ssl_referee.proto\x1a#messages_robocup_ssl_geometry.proto\x1a\x0fHandshake.proto\x1a\x0fUiOptions.proto\"\xb7\x03\n\x05State\x12%\n\x0flast_seen_world\x18\x01 \x01(\x0b\x32\x0c.proto.World\x12\x30\n\x1a\x63ommand_extrapolated_world\x18\x02 \x01(\x0b\x32\x0c.proto.World\x12\'\n\x11\x62\x61ll_camera_world\x18\x03 \x01(\x0b\x32\x0c.proto.World\x12\x34\n\x15\x62lue_robot_parameters\x18\x04 \x01(\x0b\x32\x15.proto.TeamParameters\x12\x36\n\x17yellow_robot_parameters\x18\x05 \x01(\x0b\x32\x15.proto.TeamParameters\x12&\n\x05\x66ield\x18\x06 \x01(\x0b\x32\x17.proto.SSL_GeometryData\x12#\n\x07referee\x18\x07 \x01(\x0b\x32\x12.proto.SSL_Referee\x12:\n\x18processed_vision_packets\x18\n \x03(\x0b\x32\x18.proto.SSL_WrapperPacket\x12\x35\n\x19processed_referee_packets\x18\x0b \x03(\x0b\x32\x12.proto.SSL_Referee\"W\n\x0bModuleState\x12\"\n\x0csystem_state\x18\x01 \x01(\x0b\x32\x0c.proto.State\x12$\n\nhandshakes\x18\x02 \x03(\x0b\x32\x10.proto.Handshakeb\x06proto3'
  ,
  dependencies=[World__pb2.DESCRIPTOR,RobotParameters__pb2.DESCRIPTOR,messages__robocup__ssl__wrapper__pb2.DESCRIPTOR,messages__robocup__ssl__referee__pb2.DESCRIPTOR,messages__robocup__ssl__geometry__pb2.DESCRIPTOR,Handshake__pb2.DESCRIPTOR,UiOptions__pb2.DESCRIPTOR,])




_STATE = _descriptor.Descriptor(
  name='State',
  full_name='proto.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_seen_world', full_name='proto.State.last_seen_world', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command_extrapolated_world', full_name='proto.State.command_extrapolated_world', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_camera_world', full_name='proto.State.ball_camera_world', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue_robot_parameters', full_name='proto.State.blue_robot_parameters', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yellow_robot_parameters', full_name='proto.State.yellow_robot_parameters', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field', full_name='proto.State.field', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='referee', full_name='proto.State.referee', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processed_vision_packets', full_name='proto.State.processed_vision_packets', index=7,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processed_referee_packets', full_name='proto.State.processed_referee_packets', index=8,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=641,
)


_MODULESTATE = _descriptor.Descriptor(
  name='ModuleState',
  full_name='proto.ModuleState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_state', full_name='proto.ModuleState.system_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handshakes', full_name='proto.ModuleState.handshakes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=730,
)

_STATE.fields_by_name['last_seen_world'].message_type = World__pb2._WORLD
_STATE.fields_by_name['command_extrapolated_world'].message_type = World__pb2._WORLD
_STATE.fields_by_name['ball_camera_world'].message_type = World__pb2._WORLD
_STATE.fields_by_name['blue_robot_parameters'].message_type = RobotParameters__pb2._TEAMPARAMETERS
_STATE.fields_by_name['yellow_robot_parameters'].message_type = RobotParameters__pb2._TEAMPARAMETERS
_STATE.fields_by_name['field'].message_type = messages__robocup__ssl__geometry__pb2._SSL_GEOMETRYDATA
_STATE.fields_by_name['referee'].message_type = messages__robocup__ssl__referee__pb2._SSL_REFEREE
_STATE.fields_by_name['processed_vision_packets'].message_type = messages__robocup__ssl__wrapper__pb2._SSL_WRAPPERPACKET
_STATE.fields_by_name['processed_referee_packets'].message_type = messages__robocup__ssl__referee__pb2._SSL_REFEREE
_MODULESTATE.fields_by_name['system_state'].message_type = _STATE
_MODULESTATE.fields_by_name['handshakes'].message_type = Handshake__pb2._HANDSHAKE
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['ModuleState'] = _MODULESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'State_pb2'
  # @@protoc_insertion_point(class_scope:proto.State)
  })
_sym_db.RegisterMessage(State)

ModuleState = _reflection.GeneratedProtocolMessageType('ModuleState', (_message.Message,), {
  'DESCRIPTOR' : _MODULESTATE,
  '__module__' : 'State_pb2'
  # @@protoc_insertion_point(class_scope:proto.ModuleState)
  })
_sym_db.RegisterMessage(ModuleState)


# @@protoc_insertion_point(module_scope)
