# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldBall.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.Vector2f_pb2 as Vector2f__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorldBall.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fWorldBall.proto\x12\x05proto\x1a\x0eVector2f.proto\"\x80\x01\n\tWorldBall\x12\x0c\n\x04\x61rea\x18\x01 \x01(\r\x12\x1c\n\x03pos\x18\x02 \x01(\x0b\x32\x0f.proto.Vector2f\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x1c\n\x03vel\x18\x04 \x01(\x0b\x32\x0f.proto.Vector2f\x12\r\n\x05z_vel\x18\x05 \x01(\x02\x12\x0f\n\x07visible\x18\x06 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[Vector2f__pb2.DESCRIPTOR,])




_WORLDBALL = _descriptor.Descriptor(
  name='WorldBall',
  full_name='proto.WorldBall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='area', full_name='proto.WorldBall.area', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='proto.WorldBall.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='proto.WorldBall.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vel', full_name='proto.WorldBall.vel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_vel', full_name='proto.WorldBall.z_vel', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visible', full_name='proto.WorldBall.visible', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=171,
)

_WORLDBALL.fields_by_name['pos'].message_type = Vector2f__pb2._VECTOR2F
_WORLDBALL.fields_by_name['vel'].message_type = Vector2f__pb2._VECTOR2F
DESCRIPTOR.message_types_by_name['WorldBall'] = _WORLDBALL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldBall = _reflection.GeneratedProtocolMessageType('WorldBall', (_message.Message,), {
  'DESCRIPTOR' : _WORLDBALL,
  '__module__' : 'WorldBall_pb2'
  # @@protoc_insertion_point(class_scope:proto.WorldBall)
  })
_sym_db.RegisterMessage(WorldBall)


# @@protoc_insertion_point(module_scope)
