# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldRobot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.Vector2f_pb2 as Vector2f__pb2
import proto.RobotProcessedFeedback_pb2 as RobotProcessedFeedback__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorldRobot.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10WorldRobot.proto\x12\x05proto\x1a\x0eVector2f.proto\x1a\x1cRobotProcessedFeedback.proto\"\xa3\x01\n\nWorldRobot\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1c\n\x03pos\x18\x02 \x01(\x0b\x32\x0f.proto.Vector2f\x12\r\n\x05\x61ngle\x18\x03 \x01(\x02\x12\x1c\n\x03vel\x18\x04 \x01(\x0b\x32\x0f.proto.Vector2f\x12\t\n\x01w\x18\x05 \x01(\x02\x12\x33\n\x0c\x66\x65\x65\x64\x62\x61\x63kInfo\x18\x06 \x01(\x0b\x32\x1d.proto.RobotProcessedFeedbackb\x06proto3'
  ,
  dependencies=[Vector2f__pb2.DESCRIPTOR,RobotProcessedFeedback__pb2.DESCRIPTOR,])




_WORLDROBOT = _descriptor.Descriptor(
  name='WorldRobot',
  full_name='proto.WorldRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.WorldRobot.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='proto.WorldRobot.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='proto.WorldRobot.angle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vel', full_name='proto.WorldRobot.vel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='proto.WorldRobot.w', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feedbackInfo', full_name='proto.WorldRobot.feedbackInfo', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=237,
)

_WORLDROBOT.fields_by_name['pos'].message_type = Vector2f__pb2._VECTOR2F
_WORLDROBOT.fields_by_name['vel'].message_type = Vector2f__pb2._VECTOR2F
_WORLDROBOT.fields_by_name['feedbackInfo'].message_type = RobotProcessedFeedback__pb2._ROBOTPROCESSEDFEEDBACK
DESCRIPTOR.message_types_by_name['WorldRobot'] = _WORLDROBOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldRobot = _reflection.GeneratedProtocolMessageType('WorldRobot', (_message.Message,), {
  'DESCRIPTOR' : _WORLDROBOT,
  '__module__' : 'WorldRobot_pb2'
  # @@protoc_insertion_point(class_scope:proto.WorldRobot)
  })
_sym_db.RegisterMessage(WorldRobot)


# @@protoc_insertion_point(module_scope)
