# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: World.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.WorldBall_pb2 as WorldBall__pb2
import proto.WorldRobot_pb2 as WorldRobot__pb2
import proto.RobotProcessedFeedback_pb2 as RobotProcessedFeedback__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='World.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bWorld.proto\x12\x05proto\x1a\x0fWorldBall.proto\x1a\x10WorldRobot.proto\x1a\x1cRobotProcessedFeedback.proto\"\xf3\x01\n\x05World\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\r\x12\x1e\n\x04\x62\x61ll\x18\x03 \x01(\x0b\x32\x10.proto.WorldBall\x12!\n\x06yellow\x18\x04 \x03(\x0b\x32\x11.proto.WorldRobot\x12\x1f\n\x04\x62lue\x18\x05 \x03(\x0b\x32\x11.proto.WorldRobot\x12\x36\n\x14yellow_unseen_robots\x18\x06 \x03(\x0b\x32\x18.proto.FeedbackOnlyRobot\x12\x34\n\x12\x62lue_unseen_robots\x18\x07 \x03(\x0b\x32\x18.proto.FeedbackOnlyRobotb\x06proto3'
  ,
  dependencies=[WorldBall__pb2.DESCRIPTOR,WorldRobot__pb2.DESCRIPTOR,RobotProcessedFeedback__pb2.DESCRIPTOR,])




_WORLD = _descriptor.Descriptor(
  name='World',
  full_name='proto.World',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='proto.World.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.World.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball', full_name='proto.World.ball', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yellow', full_name='proto.World.yellow', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue', full_name='proto.World.blue', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yellow_unseen_robots', full_name='proto.World.yellow_unseen_robots', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue_unseen_robots', full_name='proto.World.blue_unseen_robots', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=331,
)

_WORLD.fields_by_name['ball'].message_type = WorldBall__pb2._WORLDBALL
_WORLD.fields_by_name['yellow'].message_type = WorldRobot__pb2._WORLDROBOT
_WORLD.fields_by_name['blue'].message_type = WorldRobot__pb2._WORLDROBOT
_WORLD.fields_by_name['yellow_unseen_robots'].message_type = RobotProcessedFeedback__pb2._FEEDBACKONLYROBOT
_WORLD.fields_by_name['blue_unseen_robots'].message_type = RobotProcessedFeedback__pb2._FEEDBACKONLYROBOT
DESCRIPTOR.message_types_by_name['World'] = _WORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

World = _reflection.GeneratedProtocolMessageType('World', (_message.Message,), {
  'DESCRIPTOR' : _WORLD,
  '__module__' : 'World_pb2'
  # @@protoc_insertion_point(class_scope:proto.World)
  })
_sym_db.RegisterMessage(World)


# @@protoc_insertion_point(module_scope)
