# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Setting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rSetting.proto\x12\x05proto\"\xcb\x01\n\x07Setting\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08isYellow\x18\x02 \x01(\x08\x12\x0e\n\x06isLeft\x18\x03 \x01(\x08\x12\x12\n\nserialMode\x18\x04 \x01(\x08\x12\x10\n\x08visionIp\x18\x05 \x01(\t\x12\x12\n\nvisionPort\x18\x06 \x01(\r\x12\x11\n\trefereeIp\x18\x07 \x01(\t\x12\x13\n\x0brefereePort\x18\x08 \x01(\r\x12\x16\n\x0erobothubSendIp\x18\t \x01(\t\x12\x18\n\x10robothubSendPort\x18\n \x01(\rb\x06proto3')



_SETTING = DESCRIPTOR.message_types_by_name['Setting']
Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), {
  'DESCRIPTOR' : _SETTING,
  '__module__' : 'Setting_pb2'
  # @@protoc_insertion_point(class_scope:proto.Setting)
  })
_sym_db.RegisterMessage(Setting)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTING._serialized_start=25
  _SETTING._serialized_end=228
# @@protoc_insertion_point(module_scope)
